FROM postgres:16 as build

RUN apt update && apt -y install \
    curl \
    git \
    libclang-dev \
    build-essential \
    libreadline-dev \
    zlib1g-dev \
    flex \
    bison \
    libxml2-dev \
    libxslt-dev \
    libssl-dev \
    libxml2-utils \
    xsltproc \
    ccache \
    pkg-config \
    sudo

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install --locked cargo-pgrx && cargo pgrx init

WORKDIR /source
RUN git clone https://github.com/txpipe/mumak.git

WORKDIR /source/mumak/extension

RUN cargo pgrx package

RUN SQL_FILE=$(ls /source/mumak/extension/target/release/mumak-pg16/usr/share/postgresql/16/extension/mumak--*.sql) && \
    cp $SQL_FILE /source/mumak/extension/target/release/mumak-pg16/usr/share/postgresql/16/extension/mumak.sql

FROM postgres:16

COPY --from=build /source/mumak/extension/target/release/mumak-pg16/usr/share/postgresql/16/extension/mumak.control /usr/share/postgresql/16/extension/mumak.control
COPY --from=build /source/mumak/extension/target/release/mumak-pg16/usr/lib/postgresql/16/lib/mumak.so /usr/lib/postgresql/16/lib/mumak.so
COPY --from=build /source/mumak/extension/target/release/mumak-pg16/usr/share/postgresql/16/extension/mumak.sql /usr/share/postgresql/16/extension/mumak.sql

COPY ./docker/init-db.sh /docker-entrypoint-initdb.d/

