FROM rust:1.75-slim-buster as build

WORKDIR /app

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev cmake


COPY ./Cargo.toml ./Cargo.toml
COPY ./operator ./operator
COPY ./pgbouncer-tier-updater ./pgbouncer-tier-updater

RUN cargo build --release

FROM rust:1.74-slim-buster 
COPY --from=build /app/target/release/pgbouncer-tier-updater .
CMD ["./pgbouncer-tier-updater"]
LABEL service=proxy
