FROM rust:1.92-slim as build

WORKDIR /app

RUN apt update
RUN apt install -y build-essential pkg-config libssl-dev cmake

COPY ./operator/Cargo.lock ./Cargo.lock
COPY ./operator/Cargo.toml ./Cargo.toml
COPY ./operator/src ./src

RUN cargo build --release

FROM rust:1.92-slim
COPY --from=build /app/target/release/controller .
CMD ["./controller"]
