version: "3"

services:
  postgres_1:
    image: postgres
    container_name: postgres_1
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    ports:
      - "5432:5432"
    networks:
      - mumak-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_2:
    image: postgres
    container_name: postgres_2
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    ports:
      - "5433:5432"
    networks:
      - mumak-network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mumak-network:
    driver: bridge
