apiVersion: v1
kind: Namespace
metadata:
  name: prj-mainnet-test
---
apiVersion: demeter.run/v1alpha1
kind: MumakPort
metadata:
  name: mainnet-user
  namespace: prj-mainnet-test
spec:
  network: "mainnet"

