name: Postgres

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/postgres.yml"
      - "docker/dockerfile.postgres"
  workflow_dispatch:
    inputs:
      mumak_version:
        description: 'Mumak version to be included in the postgres image. (Defaults to latest)'
        required: false

env:
  MUMAK_VERSION: ${{github.event.inputs.mumak_version}}

jobs:
  build-images:
    continue-on-error: true

    strategy:
      matrix:
        include:
          - release_for: Linux-x86_64
            build_on: ubuntu-latest
            suffix: amd

          - release_for: Linux-arm64
            build_on: buildjet-2vcpu-ubuntu-2204-arm
            suffix: arm

    runs-on: ${{ matrix.build_on }}

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dockerfile.postgres
          push: true
          tags: ghcr.io/demeter-run/ext-mumak-postgres:${{ github.sha }}-${{ matrix.suffix }}

  build-manifest:
    needs:
      - build-images
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/demeter-run/ext-mumak-postgres

      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: |
<<<<<<< Updated upstream
            ${{github.sha}}
            latest
=======
            ghcr.io/demeter-run/ext-mumak-postgres:${{gihub.sha}}
            ghcr.io/demeter-run/ext-mumak-postgres
>>>>>>> Stashed changes
          sources: |
            ghcr.io/demeter-run/ext-mumak-postgres:${{ github.sha }}-amd
            ghcr.io/demeter-run/ext-mumak-postgres:${{ github.sha }}-arm
